version: '3'
services:
  demo-app:
    image: 431282390622.dkr.ecr.us-east-1.amazonaws.com/demo-app:1.1
    ports:
    - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

# On utilise ce fichier sur le serveur de déploiement, pour mettre en place tous les services et applications